### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by Gitsmackt** [ESX-Org/skinchanger#11]
I've installed both esx_skin + skinchanger to resources\[system]

and for some reason the menu isn't popping up after I create my character name,

I cannot see the menu to edit my character

How do I fix this?

**Comment by ElPumpo** [comment]
you mean the esx_identity menu? are you sure that all the resources are starting in the correct order?

**Comment by CroLuka** [comment]
In which order should they be, I am having same problem here.
