### ISSUE TITLE
More Customs Options

### ISSUE THREAD

**Issue by Matspyder51** [ESX-Org/skinchanger#15]
I haven't the time to write it for github, I made it for my server so I give you the informations if someone has time to add it : 
eyes_color : 
 - Max Value : 31
 -` SetPedEyeColor(playerPed, Character['eyes_color'])`
blemishes : 
 - Max Value : GetNumHeadOverlayValues(0) - 1
 - Size Max Value : 10
 - `SetPedHeadOverlay(playerPed, 0, 	Character['blemishes'], (Character['blemishes_size'] / 10) + 0.0)`

I will give you more when I will found it

**Comment by ElPumpo** [comment]
New things were recently added in
