### ISSUE TITLE
Menu not showing

### ISSUE THREAD

**Issue by Inkovskyy** [ESX-Org/skinchanger#17]
Hi, i installed esx skin and skinchanger and when im joining the server, after typing firstname, birthday day  
e.t.c, the skinchanger   menu (?) doesn't showing up. Idk what should i do. Help pls.

Maybe there is something wrong with order? :  

start mapmanager
start chat
start spawnmanager
start scoreboard
start sessionmanager
start fivem
start hardcap
start rconlog
start cron

start mysql-async
start essentialmode
start esplugin_mysql
start es_admin2
start es_extended
start esx_addonaccount
start skinchanger
start esx_skin
start esx_society
start esx_billing
start esx_datastore
start esx_license
start esx_policejob
start esx_identity

:)

**Comment by ElPumpo** [comment]
Install esx properly
