### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by AgreedBog** [ESX-Org/skinchanger#21]
Hi there,

Iam trying to make my own server and i have come to the point of character creation. now i have the issue that i see the menu and i can navigate trough it but if i change my skin, my charachter does not change with it. iam also not able to close the menu or to confirm my “changes”

loading order:

```
# you probably don't want to change these!
# only change them if you're using a server with multiple network interfaces
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"


set es_enableCustomData 1

set mysql_connection_string "server=....;database=essentialmode;userid=root;password=....."

# Initialize System Main Files
start mapmanager
start chat
start spawnmanager
start fivem
start hardcap
start rconlog
start scoreboard

# Starting Mysql-async
start mysql-async
start async
start cron
start essentialmode
start esplugin_mysql
start es_admin2
start es_extended
start esx_menu
start esx_menu_list
start esx_menu_dialog
start esx_skin
start skinchanger
start esx_addonaccount
start esx_jobs
start esx_billing
start esx_society
start esx_identity
start esx_datastore
start esx_license
start esx_clotheshop

#start fs_freemode
sv_scriptHookAllowed 1

```
[A clip of the problem](https://gyazo.com/a3a68bc6f3f9e808d7915e55d87fe2fb)

does someone know how i can fix this?

**Comment by amerem3** [comment]
Firstly skinchanger comes before esx skin you hit the enter key to confirm and if its not saving your character then you might have a database issue

**Comment by romiejo** [comment]
Same issue here, bot mostly with other identity plugins than the original. 
Can't seem to find the solution.
