### ISSUE TITLE
How to remove some clothing

### ISSUE THREAD

**Issue by keketiger** [ESX-Org/skinchanger#27]

**Comment by BackrndSource** [comment]
https://forum.fivem.net/t/esx-restrict-skin-for-new-player-when-creating/75565

**Comment by quentin3225** [comment]
`RegisterNetEvent('esx_skin:openSaveableMenu')
AddEventHandler('esx_skin:openSaveableMenu', function(submitCb, cancelCb)
	local restrict = {}
	restrict = {
		'sex',
		'face',
		'skin',
		'age_1',
		'age_2',
		'beard_1',
		'beard_2',
		'beard_3',
		'beard_4',
		'hair_1',
		'hair_2',
		'hair_color_1',
		'hair_color_2',
		'eye_color',
		'eyebrow_1',
		'eyebrow_2',
		'eyebrow_3',
		'eyebrow_4',
		'blemishes_1',
		'blemishes_2',
		'blush_1',
		'blush_2',
		'blush_3',
		'complexion_1',
		'complexion_2',
		'sun_1',
		'sun_2',
		'moles_1',
		'moles_2',
		'bodyb_1',
		'bodyb_2'
    }
    OpenSaveableMenu(submitCb, cancelCb, restrict)
end)`

I change this in my client and but when I first spawn I can see the whole with pant, shirt and all that. And when I have finished registering I see my menu with only the things I want to see. So it looks like it work but when I want to change the number of a line it switches to the previous menu with all the character option... what should I change to make the menu always the same ?

**Comment by CaosPlays** [comment]
@quentin3225 place the following below the line "local heading = 90.0" this "local restrict = true"

**Comment by kira80420** [comment]
hello i tested all that you had given but i also have the same thing quan i change value in the menu all come back

I put it this way:

RegisterNetEvent('esx_skin:openSaveableMenu')
AddEventHandler('esx_skin:openSaveableMenu', function(submitCb, cancelCb)
local restrict = true
restrict = {
'sex',
'face',
'skin',
'age_1',
'age_2',
'beard_1',
'beard_2',
'beard_3',
'beard_4',
'hair_1',
'hair_2',
'hair_color_1',
'hair_color_2',
'eye_color',
'eyebrow_1',
'eyebrow_2',
'eyebrow_3',
'eyebrow_4',
'blemishes_1',
'blemishes_2',
'blush_1',
'blush_2',
'blush_3',
'complexion_1',
'complexion_2',
'sun_1',
'sun_2',
'moles_1',
'moles_2',
'bodyb_1',
'bodyb_2'
}
OpenSaveableMenu(submitCb, cancelCb, restrict)
end)

**Comment by iTzCrutchie** [comment]
Also getting the same issue where the menu appears but as soon as you change a value it pulls up the old menu with all the options.
