### ISSUE TITLE
error skinchanger

### ISSUE THREAD

**Issue by dark00d** [ESX-Org/skinchanger#38]
hello 
I have an error when when someone bought a hat #

![ffff](https://user-images.githubusercontent.com/52639620/64078993-fadce800-cce1-11e9-8769-c59d4e4670b2.PNG)

**Comment by AMinecraftplayer** [comment]
I have this problem too. With booth version 1.0.0 and 1.0.3
With esx_clotheshop and esx_eden_slotheshop

**Comment by Lucky1316** [comment]
I also have the same problem. Need help for fixing
