### ISSUE TITLE
How can I do that when my users register the first time they appear in the square and not in different places?

### ISSUE THREAD

**Issue by Luis26x** [ESX-Org/skinchanger#47]
Hello I hope you are well,
It's not a problem, it's just a little ignorance, which I have

How can I do that when my users register the first time they appear in the square and not in different places, they have me a little crazy with that.

**Comment by Luis26x** [comment]
I'm not sure, if the question is in the right place, if it's not, I'm sorry, I'm new here.

**Comment by HumanTree92** [comment]
Go to resouces>[gamemodes]>[maps]>YOURMAPNAME>map.lua

Here is an example
```lua
spawnpoint 'a_m_y_hipster_01' { x = 76.88, y = -1398.67, z = 29.39 }
spawnpoint 'a_m_y_hipster_01' { x = 70.92, y = -1395.8, z = 29.39 }
spawnpoint 'a_m_y_hipster_01' { x = 77.24, y = -1390.79, z = 29.39 }
spawnpoint 'a_m_y_hipster_01' { x = 80.98, y = -1396.31, z = 29.39 }
spawnpoint 'a_m_y_hipster_01' { x = 79.86, y = -1398.89, z = 29.39 }
```

**Comment by HumanTree92** [comment]
This will have it set so whenever someone first spawns they will spawn at 1 of those spawnpoints at random.

**Comment by Luis26x** [comment]
a million thanks,👍🏻👍🏻💪🏻💪🏻💪🏻👌🏽
